name: customer_app
description: OhMyFood customer Flutter application
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^12.1.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  http: ^1.2.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  design_system:
    path: ../../packages/design_system
  shared_models:
    path: ../../packages/shared_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
